### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Saumya-Mishra9129** [sugarlabs/mastermind-activity#5]
> Traceback (most recent call last):
       File "/usr/bin/sugar-activity3", line 5, in <module>
           activityinstance.main()
     File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 230, in main
        instance = create_activity_instance(activity_constructor, activity_handle)
     File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 59 , in create_activity_instance
         activity = constructor(handle)
     File "/usr/share/sugar/activities/mastermind-activity/activity.py", line 54, in __init__
         self.read_file()
     File "/usr/share/sugar/activities/mastermind-activity/activity.py", line 128, in read_file
         current.append(data["balls"][x][data["level"]])
 IndexError: list index out of range

Steps to produce - Play a game till end i.e. complete whole board , press stop button to exit from activity , resume activity from journal check in logs.

**Comment by ghost** [comment]
Not able to reproduce it on UTM macos.
